# Generated by Django 4.1.5 on 2023-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='overtime_pay_rate',
            new_name='overtime',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
