# Generated by Django 4.1.5 on 2023-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_notice_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
