# Generated by Django 4.1.4 on 2023-01-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='phno',
            field=models.CharField(default='ph no', max_length=10),
        ),
    ]
