# Generated by Django 4.1.5 on 2023-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_overtime_pay_rate_payroll_overtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
