# Generated by Django 4.1.5 on 2023-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_name_notice_username_alter_notice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
