# Generated by Django 4.1.4 on 2023-01-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_employee_email_employee_name_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
