# Generated by Django 4.1.4 on 2023-01-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_employee_eid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='User',
        ),
    ]
