# Generated by Django 4.1.4 on 2023-02-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_profile_ph_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ph_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
