# Generated by Django 4.1.5 on 2023-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_payroll_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8),
        ),
    ]
