# Generated by Django 4.1.4 on 2023-01-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
