# Generated by Django 4.1.5 on 2023-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_payroll_hours_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='user_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='department',
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
    ]
