# Generated by Django 4.1.5 on 2023-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_body_notice_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sn',
            field=models.IntegerField(),
        ),
    ]
