# Generated by Django 4.1.5 on 2023-03-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_post_post_user_post_remove_post_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.post'),
            preserve_default=False,
        ),
    ]
