# Generated by Django 4.1.5 on 2023-03-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230228_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overttimeBonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_pay_rate',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
