# Generated by Django 4.1.5 on 2023-02-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_notice_department_alter_notice_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='department',
        ),
    ]
