# Generated by Django 4.1.5 on 2023-03-08 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_department_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
