# Generated by Django 4.1.5 on 2023-02-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_notice_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.CharField(default='All Departments', max_length=100),
        ),
    ]
