# Generated by Django 4.1.5 on 2023-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_payroll_net_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
