# Generated by Django 4.1.5 on 2023-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_payroll_overtime_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
    ]
