# Generated by Django 4.1.5 on 2023-03-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_payroll_overtime_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='gross_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
