# Generated by Django 4.1.5 on 2023-03-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_payroll_gross_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='basic_pay_rate',
            new_name='basic_pay',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='hours_worked',
        ),
    ]
