# Generated by Django 4.1.5 on 2023-03-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_payroll_overtime_multiplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='created_date',
            new_name='date',
        ),
    ]
