# Generated by Django 4.1.5 on 2023-03-13 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_rename_created_date_payroll_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_mac_address', message='MAC address must be in the format xx:xx:xx:xx:xx:xx', regex='^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$')])),
            ],
        ),
    ]
